### PR TITLE
Added headerOffset API to change headerOffset dynamically

### PR DESCRIPTION
**Pull request by miljenko1**
For the cases when headerOffset of an existing fixedHeader need to be
changed, introduced headerOffset() API.
Usage:  table.fixedHeader.headerOffset( topOffset );

### CODE REVIEW

**Comment by DataTables** [comment]
Looks good - thanks! I wonder if you would be willing to make it a getter as well as a setter? Most of the API methods which can be used as setters can also be used as getters, so for consistency this would be a good change.

Also, are you happy for this to be released under the MIT license?

**Comment by miljenko1** [comment]
Just added footerOffset to complete API changes started with headerOffset getter/setter

PS This is the first time I am using Git and still struggling to get it right,

**Comment by DataTables** [comment]
Was this intentionally closed?

**Comment by miljenko1** [comment]
This is the first time I am using such kind of forum and contributing to an open source project and using Git(hub). 
So the answer is - no it is not intentionally closed.
Q: did my 2nd and 3rd PR (headerOffset getter, footerOffset getter/setter) reached you?

**Comment by DataTables** [comment]
Yup - I see them. Thanks! I'll review them before the next FixedHeader release.

**Comment by DataTables** [comment]
Awesome. I've made a few little changes and added documentation, but your work will be in the next release. Thanks!

**Pull request merged**
