### PR TITLE
Fixed header shouldn't print

### PR DESCRIPTION
**Pull request by joe-meyer**

### CODE REVIEW

**Comment by DataTables** [comment]
Very good point - thanks for the PR. This should be in the other styles as well. I'm happy to include it or take an updated PR.

Are you happy for this to be released under the MIT license?

**Comment by joe-meyer** [comment]
I'm fine with it being released under MIT.

Also, i'm not super familiar with SASS / SCSS yet, but is it possible to have a base file and simply override styles as needed and then simply release compiled versions of each? Seems kind of odd to duplicate code across 4 different files. But if you'd like I can certainly update the other files (or you can merge and do it yourself really makes no difference to me).

**Comment by DataTables** [comment]
What I've done with some of the other extensions is to have a `common.scss` file which has the common styles and can just be included in all 4 styling files. The [Buttons repo](https://github.com/DataTables/Buttons/tree/master/css) uses this if you'd like to make that change.

**Comment by joe-meyer** [comment]
@DataTables ok for now I just updated the other SCSS files, the common might make more sense in the future if more common styles get added.

**Comment by DataTables** [comment]
Sounds fair - thanks for the PR.

**Pull request merged**
